### ISSUE TITLE
How to use "Fritz!Box guest WLAN" device?

### ISSUE THREAD

**Issue by n3roGit** [andig/pimatic-fritz#1]
can you explain it?

**Comment by n3roGit** [comment]
i use:

{
      "id": "FritzWlan",
      "name": "FritzWlan",
      "class": "FritzWlan",
      "interval": 120
    }

But i can only activate it. disable is not working..

**Comment by andig** [comment]
Which FB/ firmware are you using?

**Comment by n3roGit** [comment]
i use:

FRITZ!Box 6360 Cable (kdg)
FRITZ!OS 06.05

**Comment by andig** [comment]
This seems to be a problem with the 6360 and/or fw version. Workaround: set a timeout for the guest wlan so it disables itself. Wontfix for now, sorry.

**Comment by n3roGit** [comment]
Ohh ok.
i use this workaround already ;)

THX You!
