### ISSUE TITLE
error [pimatic]: Cannot find module 'smartfritz-promise'

### ISSUE THREAD

**Issue by mwittig** [andig/pimatic-fritz#16]
I have installed pimatic-fritz 0.3.0
The following message is output in the log on pimatic startup:
error [pimatic]: Cannot find module 'smartfritz-promise'

See PR #14

**Comment by n3roGit** [comment]
Here the same after Update:

15:28:00.385 [pimatic] info: Starting pimatic version 0.8.93
15:28:38.405 [pimatic] error: Cannot find module 'smartfritz-promise'
15:28:42.806 [pimatic] warn: no plugin found for device "FritzWlan" of class "FritzWlan"!

Full delete of the Plugin and reinstall dont fix the problem

**Comment by andig** [comment]
Check the source of the installed module- is the fix in?

**Comment by andig** [comment]
Raised the version number to force update.

**Comment by n3roGit** [comment]
Yes just downloaded direct from github. But no effect :(

EDIT:
After update via pimatic it works!!!!!

**Comment by andig** [comment]
Any chance to get ssh/http access to your pumatic via pm?

**Comment by mwittig** [comment]
@n3roGit @andig 

With version 0.3.1 (installed via pimatic frontend) it works fine for me now.
