### ISSUE TITLE
Unhandled rejection Error: [object Object] 

### ISSUE THREAD

**Issue by thost96** [andig/pimatic-fritz#20]
I have added pimatic-fritz to my config for switching guest wifi on and off. Now i'm getting this error: 

```
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectUncheckedCheckError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:657:22)
    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:542:21)
    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:590:10)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:669:18)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:135:10)
    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:16:14)
    at process._tickCallback (node.js:415:13)
```

here is my fritz plugin config:

```
{
      "plugin": "fritz",
      "url": "http://192.168.XXX.XXX",
      "user": "XXX",
      "password": "XXX",
      "interval": 3600
},

{
      "id": "guest-wlan",
      "name": "Gast WLAN",
      "class": "FritzWlan"
},

```

What is causing this rejection?

**Comment by andig** [comment]
Dunno. Could you try print the error object?

**Comment by cm86** [comment]
Oh i think it's the firmware of your box. Guest-Wlan is not working with the actual firmware.
ehm in pimatic i meant.
Mit freundlichen Grüßen
Chris

**Comment by thost96** [comment]
@cm86 thats could be the reason. i have a fritzbox 7490 with firmware 6.51

**Comment by cm86** [comment]
I think i habe read about the issue in the Pimatic Forum.

**Comment by Alphascrypt** [comment]
Same Problem FritzBox 7390 version 6.51.

`Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectUncheckedCheckError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:657:22)
    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:556:21)
    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)
`

**Comment by andig** [comment]
Gibts Testcode zum reproduzieren?

Viele Grüße,
Andreas

**Comment by andig** [comment]
Ps.: if its with the guest wlan functions I'm sorry- wontfix unless smbd wants to contribute a patch. 

Viele Grüße,
Andreas

**Comment by Alphascrypt** [comment]
Hast schnell geantwortet, super.
Nein dies ist einfach der der startprozess wenn ich das fritz plugin mit laden lasse. Sobald ich ein DECT Thermostat hinzufüge startet die Pimatic nicht mehr und schreibt mir das: `Invalid config: Missing property "rule,active,logging" in /rules/2, Property "class" is not a valid property in /rules/2, Property "ain" is not a valid property in /rules/2
`

**Comment by andig** [comment]
Mhm- aber die rules werden egtl. Nicht vom Plugin gemanagt. Mach bitte einen Fehler mit der Rule bei pimatic auf, gerne hier verlinken.

**Comment by andig** [comment]
@cm86 when do you get that error?

**Comment by cm86** [comment]
Hmm, ich habe aktuell keine Probleme mit deinem Plugin.
Guest-Wlan nutze ich nicht. Von daher kann ich hier nicht helfen.
Hatte es am Anfang mal versucht, nutze es aber wie gesagt nicht.

Hmm, actually i have no problems with your plugin.
I don't use the Guest-Wlan. So i can't help here so much.
Just tried at the beginning, but i'm not using it.

mfg
Chris

**Comment by Alphascrypt** [comment]
Der Fehler kommt sofort beim starten. Ich kann mir das nicht erklären.

The error comes directly on startup.

**Comment by Alphascrypt** [comment]
The thief is the new FritzOS 6.51 can u fix this problem with the new version?

**Comment by andig** [comment]
@Alphascrypt Du hast zwei Fehlermeldungen angegeben. Wann kommt welche?

**Comment by Alphascrypt** [comment]
@andig Hallo, zuerst kommt diese direkt nach der Datumsanzeige von pimatic beim start:
`Invalid config: Missing property "rule,active,logging" in /rules/2, Property "class" is not a valid property in /rules/2, Property "ain" is not a valid property in /rules/2`

Nach dem html rendering kommt diese meldung:
`Unhandled rejection Error: [object Object] at Object.ensureErrorObject (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:261:20) at Promise._rejectUncheckedCheckError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:657:22) at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:556:21) at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:604:10) at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/promise.js:679:18) at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:138:16) at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:148:10) at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic-fritz/node_modules/bluebird/js/release/async.js:17:14) at process._tickCallback (node.js:415:13)`

**Comment by andig** [comment]
Ok. Ich frag zum 3. mal ;) Hast Du zumindest für die erste Meldung einen Fehler bei Pimatic aufgemacht? Einschl. Deiner definierten Regeln? Ggf. ist der zweite nur ein Folgefehler.

**Comment by Alphascrypt** [comment]
Hallo, ja zu finden unter : [Pimatic Forum](https://forum.pimatic.org/topic/729/new-plugin-for-ip-camera-snapshot/56)

**Comment by Alphascrypt** [comment]
Ja gerade eben : [Pimatic forum](https://forum.pimatic.org/topic/1355/pimatic-fritz-guest-wlan-not-working/10)

**Comment by Alphascrypt** [comment]
Ok ich habe den Fehler gefunden.

In der neuen FritzBox version ab 6.50 muss die Anmeldung mit Benutzer und Passwort aktiviert werden. danach zieht er sich alle Informationen.

![fritz](https://cloud.githubusercontent.com/assets/14818899/15096824/12d08ae6-1509-11e6-97b7-7d274478536b.png)

**Comment by andig** [comment]
> In der neuen FritzBox version ab 6.50 muss die Anmeldung mit Benutzer und Passwort aktiviert werden. danach zieht er sich alle Informationen.

Welches Setting hattest Du vorher? Würde das gerne testen um zumindest eine sinnvolle Fehlermeldung ausgeben zu können.

**Comment by Alphascrypt** [comment]
Ich hatte zuerst Anmeldung mit dem FritzBox-Kennwort. Vor dem update auf 6.51 lief dies auch ohne Probleme.

Das könntest du in deiner Doku als wichtigen Punkt hinterlegen.

**Comment by andig** [comment]
> Ich hatte zuerst Anmeldung mit dem FritzBox-Kennwort. Vor dem update auf 6.51 lief dies auch ohne Probleme.

Kann ich nicht bestätigen. Ich habe eben auf 6.51 aktualisiert und verwende weiterhin nur Kennwort. Funktioniert wunderbar. Wie hattest Du denn die config.json eingestellt?

**Comment by Alphascrypt** [comment]
hier is der auszug der erforderlichen punkte:

Plugins:
 {
      "plugin": "fritz",
      "url": "http://192.168.178.1",
      "user": "admin",
      "password": "xxxx",
      "interval": 60
    },

Device:
{
      "id": "thermostat-1",
      "name": "Heizung Balkon",
      "class": "FritzThermostat",
      "ain": "xxxxxxxxxxxxx",
    },
    {
      "id": "temp-1",
      "name": "Wohnzimmer Temp.",
      "class": "FritzTemperatureSensor",
      "ain": "xxxxxxxxxxxxx"
    }

**Comment by andig** [comment]
Please upgrade pimatic-fritz to 0.4.1 and open new issue if problem still exists.
