### ISSUE TITLE
Guest WLAN error 

### ISSUE THREAD

**Issue by Wikibear** [andig/pimatic-fritz#21]
With the new Fritz OS Version there is an error:

https://forum.pimatic.org/topic/1355/pimatic-fritz-guest-wlan-not-working

**Comment by andig** [comment]
Guest wlan was ubfortunately never stable. Best thing would be to urge AVM support to provide an API for it. The current solution is crap :(

Sorry,
Andi

**Comment by n3roGit** [comment]
Same here with 06.50 from kdg

**Comment by andig** [comment]
Should be fixed as of https://github.com/andig/smartfritz/commit/12915a6ffaf507e7f1de3299ca14348bb4fef62d and 0.5.1 of this library.

**Comment by andig** [comment]
Lets all please move the discussion here https://github.com/andig/smartfritz/issues/5
