### ISSUE TITLE
DECT200 not showing temperature

### ISSUE THREAD

**Issue by Man-in-Black** [andig/pimatic-fritz#24]
Hi,

I've read the other issues, but none of them gives me a hint how to fix it.

I use pimatic@0.8.107 with the pimatic-fritz@0.3.3

I've never seen the temperatur within pimatic.

Is the visibility of the temperature actual disabled?
Is there a way to show the temperature?

Thank you.

Kind regards

Man-in-Black

**Comment by andig** [comment]
Look here https://github.com/andig/pimatic-fritz/blob/master/device-config-schema.coffee#L64 did you configure an additional temperature sensor with the same AIN?

**Comment by Man-in-Black** [comment]
Yes I tried this already,
But it only says "unknown" als value for the temperature

**Comment by andig** [comment]
Mhm. Does setting the semperature work? Any errors in the logfile or on the console?

**Comment by Man-in-Black** [comment]
I hope we are talking about the same problem :-)

I'm using the DECT200, the power plug, not the ComecDECT for the heating.
Here is the link for this product:
http://avm.de/produkte/fritzdect/fritzdect-200/

There is no setting to set the temperature.

**Comment by andig** [comment]
I can confirm. Do you see this in the logfile?

```
11:26:55.387 [pimatic-fritz] error: Cannot access http://fritz.box/webservices/homeautoswitch.lua?0=0&sid=b7de672fe0898db5&switchcmd=getswitchtemperature&ain=10xxxxxx: 400
Unhandled rejection (<{"error":null,"response":{"statusCode"...>, no stack trace)
```

**Comment by andig** [comment]
Please upgrade pimatic-fritz to 0.4.1 and open new issue if problem still exists.

**Comment by Man-in-Black** [comment]
Thank you very much for your effort.
I will open a new case if the problem still exists.

**Comment by Man-in-Black** [comment]
Ok just tested it with the new version, the temperature ist now showing as an extra device.
Tank you very much.
