### ISSUE TITLE
guiShowValvePosition always resets to 'false'

### ISSUE THREAD

**Issue by svenalbert** [andig/pimatic-fritz#28]
Whether I activate 'guiShowValvePosition' in the 'Edit Device' page or in the graphical Config-Editor, the value for this variable is always reset to 'false'. Other changes I make this way remain - so my changes are accepted- all but this one.

`{
      "user": "",
      "password": "xxxx",
      "plugin": "fritz",
      "active": true
    },
...
    {
      "class": "FritzThermostat",
      "id": "thermostat-wohnzimmer",
      "ain": "10971xxxx040",
      "name": "Thermostat Wohnzimmer",
      "guiShowValvePosition": false,
      "guiShowTemperatureInput": true
    }`

**Comment by andig** [comment]
Could you check if removing this line https://github.com/andig/pimatic-fritz/blob/master/fritz.coffee#L365 works for you?

**Comment by svenalbert** [comment]
Later I can test it. Do I just have to edit the line or reinstall the plug-in?

**Comment by andig** [comment]
Editing should be sufficient. 

Viele Grüße,
Andreas

**Comment by svenalbert** [comment]
Removing this line gives me `error [pimatic]: unexpected newline` an nothing is shown next to the device name in the gui.

**Comment by andig** [comment]
Please put 'pass' instead of empty line.

**Comment by svenalbert** [comment]
Now it looks like

>    customConfig:
>      # guiShowModeControl: false
>      # guiShowPresetControl: false
>      # guiShowValvePosition: false
>      pass
>    # implement env.devices.TemperatureSensor
>    _temperature: null`

and the error message is 

`error [pimatic]: pass is not defined`

**Comment by svenalbert** [comment]
So nothing new about this issue?

**Comment by andig** [comment]
> So nothing new about this issue?

Sorry- too many other things going on right now. Would be happy to accept a tested PR.

**Comment by andig** [comment]
Revisiting the code I've written some months ago I'm wondering what you expect by the `guiShowValvePosition`? Imho the CometDECT thermostat does not support retrieving this information and the setting should actually be removed?

**Comment by andig** [comment]
ping @svenalbert

**Comment by svenalbert** [comment]
sorry - was ill!
I just saw the setting and if I changed the value it wasn't saved. You are right that it should be totally removed, if the thermostat does not send a value about this - I don't know what informations are available from it.

**Comment by andig** [comment]
> You are right that it should be totally removed, if the thermostat does not send a value about this

To to get this confirmed- its on the todo list now.

**Comment by andig** [comment]
Will be live with the next package release
