### ISSUE TITLE
Aktive Verbindungen abfragen

### ISSUE THREAD

**Issue by raphael-sch** [andig/pimatic-fritz#3]
Ich würde mich freuen wenn das Plugin dahingehend erweitert wird, wenn man abfragen könnte welche devices gerade aktiv sind im wlan.
damit lässt sich dann realisieren dass sich z.b. die lichter abschalten, wenn man das haus (mit smartphone in der tasche) verlässt

**Comment by n3roGit** [comment]
I like. Aber das könntest du auch mit ping devices machen

**Comment by raphael-sch** [comment]
naja aber die ip kann sich ja ändern, und der name(bzw mac adresse) innerhalb der fritzbox bleibt ja gleich

Edit: ok hab mir das plugin mal genauer angeschaut. das basiert ja auf so ner neuen api für smart home, die nur diese beiden funktionen unterstützt. denke aber es gibt noch eine allgemeinere api für die fritz boxen, die umfangreichere funktionen unterstützt

Edit2: Stichwort: TR-064

Edit3: https://github.com/hendrikw01/tr-064

**Comment by andig** [comment]
> Stichwort: TR-064

Good suggestion. Better than screen scraping. The docs are actually here: http://avm.de/service/schnittstellen/

I'll take a look when I find some spare time...

**Comment by andig** [comment]
Unfortunately https://github.com/hendrikw01/tr-064 is not on npm yet and seems pretty much dead

**Comment by andig** [comment]
_Update_ lib is on npm now so this seems doable.

**Comment by andig** [comment]
@Raphaellll could you look at TR64 and let me know which information you're interested in? Or rather: does this need to be a part of this module? You can use the npm tr64 lib on its own.
