### ISSUE TITLE
[request] dect phone information

### ISSUE THREAD

**Issue by thost96** [andig/pimatic-fritz#32]
Hi, maybe it would be possible to get some informations about connected dect phones like the Fritzfox C5 or the Fritzfon MT-F. I would also be nice if you can start a music stream via pimatic or make a broadcast with a message or so.

**Comment by andig** [comment]
None of this is supported by the fritz api. I'd need some pointers on how to do this...

**Comment by thost96** [comment]
Okay, didn't know what the fritz api is capable of. Will have a look around, maybe this is possible. Will close this for now, if this is okay for you?
