### ISSUE TITLE
add a button for WPS-push button for guest wifi

### ISSUE THREAD

**Issue by AnduriI** [andig/pimatic-fritz#33]
Hey @andig,

nice plugin. I like the option to switch guest wifi on/off without going to my fritz.box webinterface. Is there also a way to initiate a WPS push button setup?
And can I hide the psk of the network?
Maybe also a counter how many devices are connected to guest wifi (if possible).

Thanks a lot,
Anduril

**Comment by andig** [comment]
All of this should be possible, maybe with the exception of the wps button, but honestly it's not on my priority list. Sorry- won't fix for time being.
