### ISSUE TITLE
Toggle main WIFI

### ISSUE THREAD

**Issue by ikewestbrook** [andig/pimatic-fritz#35]
Hi there,

wonderful plugin thanks for that!

Would it also be possible to control the main WIFI via switch? I would like to turn this off/on based on rules that would override the fritzbox wifi scheduling.

Thanks Kay.

**Comment by andig** [comment]
I've not found a place in the fb ui to turn off wifi- so probably no. 

Ps.: if you like it feel free to donate ;)
