### ISSUE TITLE
dect200 not working with 0.5.4

### ISSUE THREAD

**Issue by leader21** [andig/pimatic-fritz#37]
i am using the dect200 only from time to time. 
today i updated to 0.5.4 and now my plug doesn't work in pimatic anymore.

that's happening on pimatic start - looking strange, the plugin is not being compiled
![](http://www.youscreen.de/sgkbjkinn44.jpg)

there is no information at all about the device, it is shown in the gui but nothing else
![](http://www.youscreen.de/axspradkj21.jpg)

here's the debug that i got 
![](http://www.youscreen.de/jbfrubuhw32.jpg)

![](http://www.youscreen.de/kcyohnsto39.jpg)

i am using fritzbox 6360 cable from unitymedia with os 6.52

**Comment by leader21** [comment]
ok, got it working
created pull request https://github.com/andig/pimatic-fritz/pull/38

**Comment by andig** [comment]
Released 0.5.5- thanks for the quick fix!
