### ISSUE TITLE
Can't set temperature anymore

### ISSUE THREAD

**Issue by theslash** [andig/pimatic-fritz#39]
I get the following error after restarting the Pimatic Service:

error [pimatic]: Invalid config of device " thermo-badezimmer": Property "_temperature" is not a valid property

The Temperature is shown correctly, but I'm not able to set the temperature anymore, I click on the + or - but nothing happens.
This worked until a few days ago, FritzOS was 6.60 on 7490 I updated it to 6.83 now, but it didn't help.
CometDect version is 3.54

I tried to recreate the Device in Pimatic but it didn't help either.

Any Suggestions?

**Comment by andig** [comment]
Did you change anything? Update pimatic etc? Anything else in the log file?

**Comment by theslash** [comment]
Not that I'm aware, I updated another Plugin a few days ago.
I just deleted all the Comets and recreated one and just get:
Property "_temperature" is not a valid property

Pimatic Version is 0.9.38

**Comment by theslash** [comment]
Interesting is: 
when I set the temparature on the Fritzbox to a Value and then edit the Device in Pimatic it sets itself to the same temp but says "Property "_temperature" is not a valid property"

//edit:
It reads the set temp from the fritzbox after a a few minutes
When I look at the graph in Pimatic it seems to have worked until yesterday evening.

http://imgur.com/a/EF7Yl

**Comment by theslash** [comment]
Ok, Its somehow related to the Browser, doesn't work in Firefox & Chrome, works in Internet Explorer...sorry for the fuzz...

**Comment by mwittig** [comment]
@theslash I don't think your issue is related to the browser you're using. 
Note, however, the Internet Exploder is **not** supported by pimatic!!!
Do you mean "Edge" rather than IE?

nb. the typo is on purpose

**Comment by theslash** [comment]
@mwittig 
I know, pimatic works with ie + edge here on my win10 machine. 
On Firefox 52.0.1 I cant change the temp

**Comment by theslash** [comment]
I know, pimatic works here on my win 10 machine with internet explorer and egde without problems.
Just with Firefox 52.0.2 it doesnt work

**Comment by matthiasmwolf** [comment]
I have a similar [issue](https://github.com/andig/pimatic-fritz/issues/40), but setting the temperature works in my setup.

**Comment by andig** [comment]
Could you try deleting these lines https://github.com/andig/pimatic-fritz/blame/cf8fd64e25139a252c2ea85bee918fcdc653422d/fritz.coffee#L362-L365, remove the additional config setting and see if it works then?

I believe that potentially https://github.com/andig/pimatic-fritz/commit/500fbd95676de33448e27448f4136bcde4651b86 was an invalid fix.

**Comment by matthiasmwolf** [comment]
When deleting lines 362-365 (including the `customConfig:` keyword) the plugin doesn't seem to work anymore.

![image](https://cloud.githubusercontent.com/assets/8525013/24962032/ee8d48f2-1f9a-11e7-9f4e-2c33df36f7e3.png)


However, at first I only deleted lines 363-365. The plugin worked, I didn't get a warning, still the key-value-pair `"_temperature": NULL` showed up.

**Comment by mwittig** [comment]
> I believe that potentially 500fbd9 was an invalid fix.

Yes, and it still looks wrong to me! I think there is still one extra space which should be removed. _temperature should be on the same indentation level as customConfig. You can also remove _temperature if you change the getter as follows:
```
    getTemperature: -> Promise.resolve(@_temperature?null)

**Comment by andig** [comment]
> Yes, and it still looks wrong to me! I think there is still one extra space which should be removed. _temperature should be on the same indentation level as customConfig. 

That would basically revert back to the state the code was in when the issue was opened. Not running pimatic right now I'm lost.

**Comment by andig** [comment]
@theslash @matthiasmwolf could you kindly check if this finally solves it https://github.com/andig/pimatic-fritz/pull/41 ?
