### ISSUE TITLE
Open window status

### ISSUE THREAD

**Issue by delta2308151984** [andig/pimatic-fritz#42]
Hi, is it possible to add a variable to check if the thermostat detect a open window?

**Comment by andig** [comment]
Could you give an example, i.e. show the output of getDevice for a thermostat that has detected an open window?

**Comment by delta2308151984** [comment]
I would like to add a rule in pimatic like: when thermostat detect open window then ...
is there a way that you can add a $thermostat123.windowOpen variable?

**Comment by andig** [comment]
I need the actual json output of getDevice for an open window. Check the fritzapi module. 

Viele Grüße,
Andreas

**Comment by delta2308151984** [comment]
Hi, ich weiss leider nicht, was du meinst. Das überschreitet leider meine Pimatic Kenntnisse.
Vielleicht habe ich auch nicht gut erklärt, was ich eigentlich meinte.

Ich habe in Pimatic ein Fritz Dect 301. Der stellt mir ja 3 Variablen zur verfügung. Temperature, TemperatureSetPoint und synced.
Das Thermostat hat ja die Funktion, dass es ein offenes Fenster erkennt und automatisch schliesst.
Ist es möglich, dies als eine Variable bereit zu stellen, wenn es ein offenes Fenster erkannt hat?

**Comment by andig** [comment]
Ich weiss was Du meinst- nur hat Avm leider nicht dokumentiert wie man ein offenes Fenster erkennt, das müsste deshalb mit ein wenig Programmierung ausgetestet werden...

Viele Grüße,
Andreas

> Am 15.11.2017 um 21:19 schrieb danieltrapp <notifications@github.com>:
> 
> Hi, ich weiss leider nicht, was du meinst. Das überschreitet leider meine Pimatic Kenntnisse.
> Vielleicht habe ich auch nicht gut erklärt, was ich eigentlich meinte.
> 
> Ich habe in Pimatic ein Fritz Dect 301. Der stellt mir ja 3 Variablen zur verfügung. Temperature, TemperatureSetPoint und synced.
> Das Thermostat hat ja die Funktion, dass es ein offenes Fenster erkennt und automatisch schliesst.
> Ist es möglich, dies als eine Variable bereit zu stellen, wenn es ein offenes Fenster erkannt hat?
> 
> 
> 
> 
>

**Comment by delta2308151984** [comment]
Hmmm, ok. Wo finde ich denn den json output den du benötigst,oder kann ihn mir anzeigen lassen?

**Comment by andig** [comment]
> Hmmm, ok. Wo finde ich denn den json output den du benötigst,oder kann ihn mir anzeigen lassen?

Du könntest mal das hier starten: https://github.com/andig/fritzapi/blob/master/example.js

**Comment by delta2308151984** [comment]
Hier der Auszug aus der example.js

Switches: 087610355566

[087610355566] Waschmaschine
[087610355566] presence: true
[087610355566] state: true
[087610355566] temp: 16°C

Thermostats: 099950013169

[099950013169] Heizung Bad
[099950013169] temp 21.5°C°C
[099950013169] target temp 22°C°C

Raw devices

[ { identifier: '087610355566',
    id: '16',
    functionbitmask: '2944',
    fwversion: '03.87',
    manufacturer: 'AVM',
    productname: 'FRITZ!DECT 200',
    present: '1',
    name: 'Waschmaschine',
    switch: { state: '1', mode: 'manuell', lock: '0', devicelock: '0' },
    powermeter: { power: '0', energy: '120401' },
    temperature: { celsius: '160', offset: '0' } },
  { identifier: '099950013169',
    id: '17',
    functionbitmask: '320',
    fwversion: '04.53',
    manufacturer: 'AVM',
    productname: 'FRITZ!DECT 301',
    present: '1',
    name: 'Heizung Bad',
    temperature: { celsius: '215', offset: '-5' },
    hkr: 
     { tist: '43',
       tsoll: '44',
       absenk: '36',
       komfort: '44',
       lock: '0',
       devicelock: '0',
       errorcode: '0',
       batterylow: '0',
       nextchange: [Object] } } ]

**Comment by andig** [comment]
Das ist gut, nur ist im Block für den 301 nirgendwo zu erkennen dass ein Fenster offen wäre. Falls das der Testfall war ist es leider nicht sichtbar?

**Comment by delta2308151984** [comment]
Ich habe extra den Fenster offen Knopf am Thermostat manuell betätigt. In der Fritzbox wird dann auch ein Schneeflocken Symbol eingeblendet. Aber im output kann ich auch nichts davon sehen. 
Schade, dann überträgt er diese Info wohl nicht.

**Comment by andig** [comment]
Kannst Du mir das Html der FB Oberfläche exportieren?

Viele Grüße,
Andreas

**Comment by delta2308151984** [comment]
[FRITZ!Box 7490.html.zip](https://github.com/andig/pimatic-fritz/files/1480139/FRITZ.Box.7490.html.zip)

**Comment by danieltrapp** [comment]
Hier nochmal mit Firefox exportiert.

[FRITZ!Box 7490 firefox.html.zip](https://github.com/andig/pimatic-fritz/files/1480163/FRITZ.Box.7490.firefox.html.zip)

**Comment by delta2308151984** [comment]
Hier nochmal mit Firefox exportiert.

[FRITZ!Box 7490 firefox.html.zip](https://github.com/andig/pimatic-fritz/files/1480167/FRITZ.Box.7490.firefox.html.zip)

**Comment by andig** [comment]
Danke, das hilft schonmal. Ich schaue ob da was möglich ist...

**Comment by andig** [comment]
Schau mal ob die Funktion für Dich funktioniert:


    module.exports.getWindowOpenState = function(sid, ain, options)
    {
        var req = {
            method: 'POST',
            form: {
                sid: sid,
                xhr: 1,
                no_sidrenew: '',
                page: 'sh',
            }
        };

        return Promise.join(
            module.exports.getDevice(sid, ain, options),
            httpRequest('/data.lua', req, options),
        function(device, body) {
            $ = cheerio.load(body);

            var elems = $('td.iconrow[datalabel="' + device.name + '"] ~ td.temperature');
            if (elems.length == 1) {
                return $('img[src~=icon_window_open]', elems[0]).length == 1;
            }

            return false;
        });
    };

Ist leider etwas hacky da die FB Oberfläche keine AINs enthält...

**Comment by delta2308151984** [comment]
Vielen Dank für deine Mühe. Ich habe das jetzt in ~/pimatic-app/node_modules/pimatic-fritz/node_modules/fritzapi/index.js eingebaut, aber so wirklich klappt das nicht. 
Sorry, wahrscheinlich stell ich mich einfach zu blöd an ;-)

**Comment by andig** [comment]
Das ist nur erstmal die Basisfunktion. Die kannst Du mal anrufen um zu schauen ob sie Dein Fenster richtig detektiert, nicht mehr und nicht weniger. An pimatic kommt da erstmal noch gar nix an...

**Comment by delta2308151984** [comment]
Ich habe jetzt den ganzen Tag versucht, dein Code sinnvoll einzubauen. Aber weder in der index.js oder in der example.js konnte ich ihn aufrufen. Ohne Java Kenntnisse, ist das leider nicht so einfach.
Falls du noch Lust und Zeit hast, mir da weiter zu helfen wäre das super. Wenn nicht, könnt ichs auch verstehen ;-)

**Comment by andig** [comment]
> Wenn nicht, könnt ichs auch verstehen ;-)

Wir kriegen das zusammen hin. Ich dachte an sowas banales wie Du schonmal getestet hattest:

    var fritz = require('./index.js');

    var options = {
        "url": "http://fritz.box"
    };

    var username = "xx";
    var password = "xx";

    fritz.getSessionID(username, password, options).then(function(sid) {
        console.log("SID: " + sid);

        fritz.getWindowOpenState(sid, "0999500xxxx").then(function(state) {
            console.log(state);
        });
    })
    .catch(function(error) {
        console.error(error);
    });

**Comment by delta2308151984** [comment]
Danke!
Da bekomm ich immer folgende Meldung:

SID: 0faeb68a2825077c
[TypeError: fritz.getWindowOpenState is not a function]

**Comment by andig** [comment]
Ok. Und hast Du die Funktion auch die die verwendete index.js Datei mit eingebaut?

**Comment by delta2308151984** [comment]
Sorry, mein Fehler ;-)
Hab die Identifikationsnummer angepasst, aber bekomme:

SID: 762e61f995983695
false

**Comment by andig** [comment]
> aber bekomme:

In dem Moment wo das Fenster offen ist und die FB Dir das auch anzeigt? Hast Du ncohmal einen Screenshot der FB Oberfläche (cpuidle@gmx.de)?

**Comment by danieltrapp** [comment]
Ja, habe es zur gleichen Zeit ausgeführt, als es inder FB angezeigt wird.

![fritzbox](https://user-images.githubusercontent.com/25320876/32980899-22adb528-cc6f-11e7-9a25-f9c8f17afba9.png)

**Comment by andig** [comment]
Das ist... schlecht. Wenn Du Dich traust bzw. mir vertraust kann Du mir per Mail Logindaten für Deine FB schicken dann könnte ich's testen.

**Comment by danieltrapp** [comment]
An welche Mailadresse soll ich sie dir schicken?

**Comment by andig** [comment]
cpuidle@gmx.de

**Comment by andig** [comment]
@danieltrapp danke für die Hilfe. `fritzapi 0.10.1` hat jetzt die notwendige `getWindowOpen` Funktion. Es wird allerdings noch ein wenig dauern bis ich pimatic aktualisieren werde.

**Comment by delta2308151984** [comment]
Super, vielen Dank!

**Comment by andig** [comment]
@danieltrapp schau mal bitte hier: https://github.com/andig/pimatic-fritz/pull/45 (ungetestet). Sollte mit jeden Gerät inkl. HAN FUN funktionieren das einen alarm state zurück gibt.

**Comment by andig** [comment]
Mit 0.6.6 implementiert.
