### ISSUE TITLE
[Request] Support DECT ULE Sensors from other vendors

### ISSUE THREAD

**Issue by mwittig** [andig/pimatic-fritz#44]
Apparently, it is possible to integrate DECT ULE sensors from other vendors, like the Telekom Door sensor, with the Fritz!Box Smart Home solution. Is it possible to provide support for this as part of the plugin?

https://www.digitalzimmer.de/artikel/test/fritzbox-akzeptiert-han-fun-sensoren-anderer-hersteller/

See also: https://forum.pimatic.org/topic/4272/optical-door-window-sensor

**Comment by andig** [comment]
Glad to add to fritzapi and this plugin, but would need a device for testing.

@mwittig tried to contact you numerous times regarding https://github.com/andig/pimatic-fritz/issues/29. It's kinda stale now but still open?

**Comment by dasmaetthes** [comment]
@andig How could I support you with testing? I want to buy some optical window sensor

**Comment by xG3n1uS** [comment]
I've bought the Optical Window/Door Sensor from Telekom Magenta Smarthome two weeks ago.

I could connect it successfully to my FritzBox 7490 with FRITZ!OS 6.93

If I do a http-request to the FritzBox with the AHA-Interface I get the following XML-Response for the sensor.

If the sensor is opened the alert state changes to 1.

> <devicelist version="1">
	<device identifier="11934 0095280-1" id="2000" functionbitmask="8208" fwversion="0.0" manufacturer="0x0feb" productname="HAN-FUN">
		<present>1</present>
		<name>HAN-FUN #4: Unit #1</name>
		<etsiunitinfo>
			<etsideviceid>409</etsideviceid>
			<unittype>514</unittype>
			<interfaces>256</interfaces>
		</etsiunitinfo>
		<alert>
			<state>0</state>
		</alert>
	</device>
</devicelist>


Hope that helps you. If I can do more, just tell me. I'm happy to test and don't need to use my python workaround with a dummy sensor.

**Comment by andig** [comment]
I‘ve got homekit support working (https://github.com/andig/homebridge-fritz), pimatic to follow.

**Comment by andig** [comment]
@mwittig is there any way to get in contact with you? my GH comments seem to get lost :(

**Comment by andig** [comment]
The contact sensor PR should be ready for testing now. Ping @dasmaetthes @xG3n1uS @mwittig

**Comment by xG3n1uS** [comment]
![screenshot_20180425-215805](https://user-images.githubusercontent.com/38210769/39269900-80d73066-48d4-11e8-828b-69961c80efd4.jpg)
I've installed the new version. Plugin detects the contact sensor, but in the events it always show me opened. No matter it's closed or open.

**Comment by andig** [comment]
What sensor model is that- Telekom? Could you log the variable that geta passed to setContact?

**Comment by xG3n1uS** [comment]
It's from Telekom.

How can I log the variable?

**Comment by xG3n1uS** [comment]
Found it.
When closed
![20180425_222940](https://user-images.githubusercontent.com/38210769/39271137-6a559d88-48d8-11e8-86e7-caa7d67e5838.png)

when opened
![screenshot_20180425-223022](https://user-images.githubusercontent.com/38210769/39271146-743534da-48d8-11e8-9b1d-1349df1a78e6.jpg)

**Comment by xG3n1uS** [comment]
In Graph-page the attribute changes, but it's inverse. 

In example below the contact is open, variable is 1, but last state in Graph is closed
![screenshot_20180425-223601](https://user-images.githubusercontent.com/38210769/39271471-72a9dbec-48d9-11e8-8971-64d943474e2b.jpg)

**Comment by andig** [comment]
Oh, seems pimatic is interpreting the other way round. Can you simply try inverting the value in line 534:

            @_setContact(1-devices[0].alert.state)

**Comment by xG3n1uS** [comment]
In Graph it's correct now.

**Comment by andig** [comment]
Published as 0.6.6, please upgrade.

**Comment by xG3n1uS** [comment]
So only problem left is, that the label is always shown as **opened** on the Pages. How can this be fixed?

![grafik](https://user-images.githubusercontent.com/38210769/39625214-c7411e08-4f9c-11e8-8074-eedf02694339.png)



Is it possile to get the Option xClosedLabel and xOpenedLabel so it's possible to set own labels (in German for instance).

![grafik](https://user-images.githubusercontent.com/38210769/39625379-6ad25eec-4f9d-11e8-9591-0106591f2feb.png)

**Comment by andig** [comment]
> So only problem left is, that the label is always shown as opened on the Pages. How can this be fixed?

I'm a bit confused. That sounds more like a problem of the Pimatic contact sensor than of this extension? If the chart is right then so should be the label display. 

Wouldn't it make sense to open an issue with pimatic or discuss in the forums instead of fixing here?

**Comment by xG3n1uS** [comment]
I'm also using the contact sensor from the Homeduino plugin and there it works. That's why I thought it's related to Fritz plugin.

**Comment by xG3n1uS** [comment]
Maybe the contact attribute must be true or false not 1 or 0 for pimatic.

**Comment by andig** [comment]
@xG3n1uS did you discuss this in the pimatic forums?

**Comment by andig** [comment]
Closing due to missing updates.
