### ISSUE TITLE
Guest wlan with version 7

### ISSUE THREAD

**Issue by n3roGit** [andig/pimatic-fritz#47]
The guest wlan is changed in fritz version 7. 
We need some improvement here to use it again

**Comment by andig** [comment]
With so little information I can only guess. Do you mean https://github.com/andig/homebridge-fritz/issues/49? That‘s an issue in the current firmware that AVM is working on.

**Comment by n3roGit** [comment]
Yes I think so

**Comment by andig** [comment]
This should be fixed by updating to a later fritzOS
