### ISSUE TITLE
FritzOS7 und Fritz Dect 200 timeout

### ISSUE THREAD

**Issue by delta2308151984** [andig/pimatic-fritz#49]
Hi, FritzDect200 Schalter lassen sich nicht schalten. Bekomme ein timeout Fehler.
Wenn ich die Schalter mit der MyFritz App Schalte, wird der Zustand in pimatic auch geändert.

Edit: Der Schalter wird erst nach über 3 Minuten Verzögerung geschaltet.

Ich hab ich den Plugin und Schalter Einstellungen Polling auf 5 stehen. Eine Änderung des Wertes hilft auch nicht.

**Comment by andig** [comment]
Gleiche Frage wie immer- debug log?

**Comment by delta2308151984** [comment]
Es wird nichts als debug log geschrieben. Habe nur info, warn und error messages. 
Das sind die error Meldungen:

error [pimatic-tradfri]: Observe device esstisch-dummy error: tradfri hub doesn't have configured this device
20:38:55error [pimatic]: Could not parse rule "when $tradfri_65543.dimlevel < 2 then turn Sofa off": Could not find an provider that decides next predicate of "$tradfri_65543.dimlevel < 2".
20:38:55error [pimatic]: Could not parse rule "when alle-lampen is turned off then turn Esstisch off and turn Sofa off and turn TV off and turn Anrichte off and turn Flur (oben) off and turn Wohnzimmer Decke off and turn Bett Anne off and turn Bett Daniel off and turn Treppe off": Could not find an provider that provides the next action of "turn Anrichte off and turn Flur (oben) off and turn Wohnzimmer Decke off and turn Bett Anne off and turn Bett Daniel off and turn Treppe off".
20:38:55error [pimatic]: Could not parse rule "when alle-lampen is turned on then turn Esstisch on and turn Sofa on and turn TV on and turn Anrichte on and turn Flur (oben) on and turn Wohnzimmer Decke on and turn Treppe on and turn Bett Anne on and turn Bett Daniel on": Could not find an provider that provides the next action of "turn Anrichte on and turn Flur (oben) on and turn Wohnzimmer Decke on and turn Treppe on and turn Bett Anne on and turn Bett Daniel on".
20:38:55error [pimatic]: Could not parse rule "when Alles aus is pressed then turn Sofa off and turn Anrichte off and turn TV off and turn Treppe off and turn Flur (oben) off and turn Bett Anne off and turn Bett Daniel off and turn Esstisch off and turn Wohnzimmer Decke off and turn Alle Lampen off and turn Stern off and turn Baum Fenster off and turn Bogen Fenster off": Could not find an provider that provides the next action of "turn Anrichte off and turn TV off and turn Treppe off and turn Flur (oben) off and turn Bett Anne off and turn Bett Daniel off and turn Esstisch off and turn Wohnzimmer Decke off and turn Alle Lampen off and turn Stern off and turn Baum Fenster off and turn Bogen Fenster off".
20:38:44error [pimatic]: Invalid config of device "iphone-anne": Property "hap" is not a valid property
20:38:44error [pimatic]: Invalid config of device "iphone-daniel": Property "hap" is not a valid property
20:38:44error [pimatic]: Invalid config of device "waschmaschine": Property "hap" is not a valid property
20:38:43error [pimatic]: Invalid config of device "alle-lampen": Property "hap" is not a valid property
20:38:43error [pimatic]: Invalid config of device "wake-diskstation": Property "hap" is not a valid property
20:38:43error [pimatic]: Invalid config of device "lampe9": Property "hap" is not a valid property

**Comment by delta2308151984** [comment]
Sorry, lag an meiner Installation. Hab Pimatic gelöscht, und alle Plugins neu installiert. Jetzt läufts.
