### ISSUE TITLE
Fehler bei Verbindung zu FritzDECT

### ISSUE THREAD

**Issue by fichte5** [andig/pimatic-fritz#5]
Hi Andreas,
what a cool pimatic-plugin to control the FritzDECT devices, but I can't connect to my DECT devices.
What I have done:
- Create a new user for Fritzbox
- Check the possibility to connect for this new user by Myfritz.net (Login ok on Fritzbox event list, device are listet on MyFritz GUI with state and AIN)
- load current pimatic-fritz Plugin in plugins[] of config.json
  {
    "plugin": "fritz",
    "url": "http://fritz.box",
    "user": "name",
    "password": "pw",
    "interval": 300
  }, 
- define FritzDECT device in devices[] of config.json:
  {
    "id": "Dect1",
    "name": "Fritz outlet",
    "class": "FritzOutlet",
    "ain": "08xxx xxxxxxx"
  } 
- restart pimatic

pimatic-daemon.log:
06:05:40.142 [pimatic] info: Starting pimatic version 0.8.69
06:05:41.915 [pimatic] info: Loading plugin: "pimatic-cron" (0.8.5)
06:05:42.738 [pimatic] info: Loading plugin: "pimatic-mobile-frontend" (0.8.64)
06:05:44.204 [pimatic] info: Loading plugin: "pimatic-ping" (0.8.5)
06:05:44.282 [pimatic] info: Loading plugin: "pimatic-fritz" (0.2.2)
06:05:45.694 [pimatic] info: Loading plugin: "pimatic-openweather" (0.8.9)
06:05:45.993 [pimatic-cron] info: the time is: Thu Jun 04 2015 06:05:45 GMT+0200 (CEST)
06:05:46.602 [pimatic] info: New device "Fritz outlet"...
06:05:46.701 [pimatic-fritz] warn: Re-establishing session at http://fritz.box
06:05:46.995 [pimatic-mobile-frontend] info: packing static assets
06:05:47.774 [pimatic-mobile-frontend] info: packing static assets finished
06:05:47.786 [pimatic-mobile-frontend] info: rendering html
06:05:54.221 [pimatic-mobile-frontend] info: rendering html finished
06:05:54.270 [pimatic] info: Listening for HTTP-request on port 8080...
06:05:54.382 [pimatic-fritz] warn: Re-establishing session at http://fritz.box
06:05:55.057 [pimatic-fritz] error: Cannot access http://fritz.box/webservices/homeautoswitch.lua?0=0&sid=0000000000000000&switchcmd=getswitchlist: 403
06:05:55.181 [pimatic-fritz] error: Cannot access http://fritz.box/webservices/homeautoswitch.lua?0=0&sid=0000000000000000&switchcmd=getswitchstate&ain=08xxx xxxxxxx: 403

Event list of Fritzbox:
06:05:55    Anmeldung an der FRITZ!Box Benutzeroberfläche von IP-Adresse xx.xx.xx.xx gescheitert (falsches Kennwort).

So it seems that login to Fritzbox with correct username/password failed for this.
I already tried with another user/password without success. And changed entry "fritz.box" to real ip  address too.
Did you have any suggestions what to do?

**Comment by andig** [comment]
> Check the possibility to connect for this new user by Myfritz.net
> `06:05:55 Anmeldung an der FRITZ!Box Benutzeroberfläche von IP-Adresse xx.xx.xx.xx gescheitert`

I'm not using Myfritz, but is it possible that myfritz and the fritzbox use different credentials? Are you able to login to the box itself using `name/pw`?

**Comment by fichte5** [comment]
Perfect hint, my Fritzbox was configured for local login only by password. 
Now it is working.
Another question: Is it possible to extend the plugin functionality to track also the temperature of Fritz!Dect200 devices? I have found details for AHA API on http://www.tdressler.net/ipsymcon/fritz_aha.html
Tnx a lot, Andi!

**Comment by andig** [comment]
>  Is it possible to extend the plugin functionality to track also the temperature of Fritz!Dect200 devices?

Yes, the smartfritz-promise library at https://github.com/andig/smartfritz already supports that.

Don't have any time though, feel free to submit a pr.
